## Initializing different types of arrays

In [1]:
import numpy as np

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# All 0s matrix
np.zeros((2,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
# All 1s matrix
np.ones((4,2,2), dtype='int32') 

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [9]:
# Any other number matrix
np.full((2,2), 99, dtype='float32') 

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [12]:
# Any oter number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [13]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.27521633, 0.14817021],
       [0.49433826, 0.13081552],
       [0.37466386, 0.10670027],
       [0.95271814, 0.10083123]])

In [15]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.02282413, 0.26614034, 0.45573301, 0.61081425, 0.62627931,
        0.30069648, 0.63861213],
       [0.95224035, 0.68183798, 0.61064286, 0.47528705, 0.28170887,
        0.26260746, 0.96789466]])

In [16]:
# Random Integer Values
np.random.randint(7)

5

In [21]:
# Random Integer Values
np.random.randint(-4,8, size=(3,3))

array([[ 0, -4, -1],
       [ 0,  0,  2],
       [-3, -4,  4]])

In [23]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
## Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [42]:
output = np.ones((5,5))
# print(output)
z = np.zeros((3,3))
z[1,1] = 9
# print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!

In [44]:
# Using copy() method we make a copy of an array and don't modify the original
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]
