## Load in NumPy (remember to pip install numpy first)

In [3]:
import numpy as np

## The basics

In [20]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get the Dimension
a.ndim

1

In [8]:
# Get Shape
a.shape

(3,)

In [15]:
# Get Type
a.dtype

dtype('int16')

In [23]:
# Get Size (in bytes) (Floats are bigger than integers in size, if you don't define it specifically)
a.itemsize
b.itemsize

8

In [22]:
# Get Total Size
a.size * a.itemsize
# a.nbytes is another option to get the same result

12