## INDEXING - Accessing / Changing specific elements, rows, columns, etc

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
# Get a specific element [r,c]
a[1,5]

13

In [ ]:
# Get a specific row
a[0, :]

In [7]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [9]:
# [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [17]:
# Change elements
a[1,5] = 20
a[:,2] = 5
a[:,4] = [11,22]
print(a)

[[ 1  2  5  4 11  6  7]
 [ 8  9  5 11 22 20 14]]


In [18]:
# 3D example
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
# Get a specific element(work outside in)
b[0,1,1]

4

In [25]:
# Replace elements
b[:,1,:] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])