## Mathematics

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a + 2
# a += 2

array([ 7,  8,  9, 10])

In [14]:
a - 2

array([3, 4, 5, 6])

In [15]:
a * 2

array([10, 12, 14, 16])

In [16]:
a / 2

array([2.5, 3. , 3.5, 4. ])

In [17]:
b = np.array([1,0,1,0])
a + b

array([6, 6, 8, 8])

In [18]:
a ** 2

array([25, 36, 49, 64])

In [23]:
# Take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [22]:
# Take the cos
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

## Linear Algebra

In [27]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [28]:
# Finde the determinant
c = np.identity(3)
np.linalg.det(c)

1.0