# Matrix operations

In [2]:
import numpy as np 

In [3]:
A = np.array([
    [2,5,7],
    [1,2,3],
    [7,8,2]
])

print(A)

[[2 5 7]
 [1 2 3]
 [7 8 2]]


In [4]:
B = np.array([
    [8,0,1], 
    [0,3,4],
    [1,0,7]
])
print(B)

[[8 0 1]
 [0 3 4]
 [1 0 7]]


In [21]:
print('Addition:\n',A+B)
print("-" * 15)
print('Subtraction:\n',A-B)
print("-" * 15)
print('Multiplication method 1:\n',  A.dot(B))
print("-" * 15)
print('Multiplication method 2:\n',  np.dot(A,B))
print("-" * 15)
print('Multiplication method 3:\n',  np.matmul(A,B))
print("-" * 15)
print('Multiplication method 4:\n',  A@B)


Addition:
 [[10  5  8]
 [ 1  5  7]
 [ 8  8  9]]
---------------
Subtraction:
 [[-6  5  6]
 [ 1 -1 -1]
 [ 6  8 -5]]
---------------
Multiplication method 1:
 [[23 15 71]
 [11  6 30]
 [58 24 53]]
---------------
Multiplication method 2:
 [[23 15 71]
 [11  6 30]
 [58 24 53]]
---------------
Multiplication method 3:
 [[23 15 71]
 [11  6 30]
 [58 24 53]]
---------------
Multiplication method 4:
 [[23 15 71]
 [11  6 30]
 [58 24 53]]


### How to find inverse of a matrix

In [22]:
print(np.linalg.inv(A))
# See what is a singular matrix

[[-1.53846154  3.53846154  0.07692308]
 [ 1.46153846 -3.46153846  0.07692308]
 [-0.46153846  1.46153846 -0.07692308]]


### Element-wise matrix multiplication

In [23]:
print(A*B)

[[16  0  7]
 [ 0  6 12]
 [ 7  0 14]]


### How to compute eigenvalues of a matrix

In [24]:
print(np.linalg.eigvals(A))

[11.72403766 -5.52328145 -0.2007562 ]
